config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :acts

  resources :kpis

  resources :plans

  get 'welcome/index'
  root 'plans#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/act.rb
class Act < ActiveRecord::Base
end

app/models/kpi.rb
class Kpi < ActiveRecord::Base
	has_many :acts
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :kpis
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :plans

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts
  # GET /acts.json
  def index
    @acts = Act.all
  end

  # GET /acts/1
  # GET /acts/1.json
  def show
  end

  # GET /acts/new
  def new
    @act = Act.new(kpi_id: params[:kpi_id])
  end

  # GET /acts/1/edit
  def edit
  end

  # POST /acts
  # POST /acts.json
  def create
    @act = Act.new(act_params)
    @act.kpi_id = params[:kpi_id]

    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render :show, status: :created, location: @act }
      else
        format.html { render :new }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acts/1
  # PATCH/PUT /acts/1.json
  def update
    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_to @act, notice: 'Act was successfully updated.' }
        format.json { render :show, status: :ok, location: @act }
      else
        format.html { render :edit }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act.destroy
    respond_to do |format|
      format.html { redirect_to acts_url, notice: 'Act was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_act
      @act = Act.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def act_params
      params.require(:act).permit(:desc, :target)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/kpis_controller.rb
class KpisController < ApplicationController
  before_action :set_kpi, only: [:show, :edit, :update, :destroy]

  # GET /kpis
  # GET /kpis.json
  def index
    @kpis = Kpi.all
  end

  # GET /kpis/1
  # GET /kpis/1.json
  def show
  end

  # GET /kpis/new
  def new
    @kpi = Kpi.new(plan_id: params[:plan_id])
  end

  # GET /kpis/1/edit
  def edit
  end

  # POST /kpis
  # POST /kpis.json
  def create
    @kpi = Kpi.new(kpi_params)
    @kpi.plan_id = params[:plan_id]

    respond_to do |format|
      if @kpi.save
        format.html { redirect_to @kpi, notice: 'Kpi was successfully created.' }
        format.json { render :show, status: :created, location: @kpi }
      else
        format.html { render :new }
        format.json { render json: @kpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kpis/1
  # PATCH/PUT /kpis/1.json
  def update
    respond_to do |format|
      if @kpi.update(kpi_params)
        format.html { redirect_to @kpi, notice: 'Kpi was successfully updated.' }
        format.json { render :show, status: :ok, location: @kpi }
      else
        format.html { render :edit }
        format.json { render json: @kpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kpis/1
  # DELETE /kpis/1.json
  def destroy
    @kpi.destroy
    respond_to do |format|
      format.html { redirect_to kpis_url, notice: 'Kpi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kpi
      @kpi = Kpi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kpi_params
      params.require(:kpi).permit(:description, :responsibility, :milestone, :plan_id)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
    @kpis = Kpi.all
    @acts = Act.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new(user_id: params[:user_id])
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:goal)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kpis_helper.rb
module KpisHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/acts/_aselect.html.erb
<% @acts.each do |act| if act.kpi_id == k_id %>
  <ul>
    <li>
      <div class="act"><span class="atitle">Action: </span><%= act.desc %> | <span class="atitle">Target: </span><%= act.target %><span class="actionSet"><%= link_to image_tag("edit.png"), edit_act_path(act) %> | <%= link_to image_tag("delete.png"), act, method: :delete, data: { confirm: 'Are you sure?' } %></span></div>
    </li>
  </ul>
  <% end %>
<% end %>

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>
<%= hidden_field_tag :kpi_id, params[:kpi_id] %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
      <% @act.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc, 'Description' %><br>
    <%= f.text_field :desc %>
  </div>
  <br>
  <div class="field">
    <%= f.label :target %><br>
    <%= f.text_field :target %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Create Action' %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<h1>Editing Action</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Show', @act %> |
	<%= link_to 'Back', acts_path %>
</p>

app/views/acts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Acts</h1>

<table>
  <thead>
    <tr>
      <th>Desc</th>
      <th>Target</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acts.each do |act| %>
      <tr>
        <td><%= act.desc %></td>
        <td><%= act.target %></td>
        <td><%= link_to 'Show', act %></td>
        <td><%= link_to 'Edit', edit_act_path(act) %></td>
        <td><%= link_to 'Destroy', act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Act', new_act_path %>

app/views/acts/new.html.erb
<h1>New Action</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Back', plans_path %>
</p>

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desc:</strong>
  <%= @act.desc %>
</p>

<p>
  <strong>Target:</strong>
  <%= @act.target %>
</p>

<p>
	<%= link_to 'Edit', edit_act_path(@act) %> |
	<%= link_to 'Back', plans_path %>
</p>

app/views/kpis/_form.html.erb
<%= form_for(@kpi) do |f| %>
<%= hidden_field_tag :plan_id, params[:plan_id] %>
  <% if @kpi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kpi.errors.count, "error") %> prohibited this kpi from being saved:</h2>

      <ul>
      <% @kpi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label :responsibility %><br>
    <%= f.text_field :responsibility %>
  </div>
  <br>
  <div class="field">
    <%= f.label :milestone %><br>
    <%= f.datetime_select :milestone %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kpis/_select.html.erb
<% @kpis.each do |kpi| k_id = kpi.id; if kpi.plan_id == p_id %>
  <ul>
    <li>
      <div class="kpi"><span class="ktitle">KPI: </span><%= kpi.description %> | <span class="ktitle">Responsibility: </span><%= kpi.responsibility %> | <span class="ktitle">Milestone: </span><%= kpi.milestone %><span class="actionSet"><%= link_to image_tag("edit.png"), edit_kpi_path(kpi) %> | <%= link_to image_tag("delete.png"), kpi, method: :delete, data: { confirm: 'Are you sure?' } %></span></div>
    <%= render :partial => "acts/aselect", locals: {k_id: k_id} %>
    </li>
  </ul>
  <% end %>
<% end %>

app/views/kpis/edit.html.erb
<h1>Editing Kpi</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Show', @kpi %> |
	<%= link_to 'Back', plans_path %>
</p>

<p>
	<%= link_to 'Add new Action', new_act_path(:kpi_id=>@kpi.id) %>
</p>

app/views/kpis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kpis</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Responsibility</th>
      <th>Milestone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kpis.each do |kpi| %>
      <tr>
        <td><%= kpi.description %></td>
        <td><%= kpi.responsibility %></td>
        <td><%= kpi.milestone %></td>
        <td><%= link_to 'Show', kpi %></td>
        <td><%= link_to 'Edit', edit_kpi_path(kpi) %></td>
        <td><%= link_to 'Destroy', kpi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kpi', new_kpi_path %>

app/views/kpis/new.html.erb
<h1>New Kpi</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Back', plans_path %>
</p>

app/views/kpis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kpi.description %>
</p>

<p>
  <strong>Responsibility:</strong>
  <%= @kpi.responsibility %>
</p>

<p>
  <strong>Milestone:</strong>
  <%= @kpi.milestone %>
</p>

<p>
	<%= link_to 'Edit', edit_kpi_path(@kpi) %> |
	<%= link_to 'Back', plans_path %>
</p>

<p>
	<%= link_to 'Add new Action', new_act_path(:kpi_id=>@kpi.id) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Action Plan Tracking System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<p class="navbar-text pull-right">
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
</p>
<%= yield %>

</body>
</html>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Show', @plan %> |
	<%= link_to 'Back', plans_path %>
</p>

<p>
	<%= link_to 'Add new KPI', new_kpi_path(:plan_id=>@plan.id) %>
</p>

app/views/plans/index.html.erb
<script src="http://code.jquery.com/jquery-git1.min.js"></script>
<script src="/assets/jquery-sortable-lists.js"></script>

<p id="notice"><%= notice %></p>

<h1>Action Plans</h1>

<p>To add a new KPI to an existing Plan, click on edit plan. Then, add new KPI.</p>
<p>To add a new Action to an existing KPI, click on edit KPI. Then, add new Action.</p>

<br>

<%= link_to 'New Plan', new_plan_path %>

<ul class="sTree2 listsClass" id="sTree2">
  <% @plans.each do |plan| p_id = plan.id; if plan.user_id == current_user.id %>
  <li>
    <div><%= plan.goal %><span class="actionSet"><%= link_to image_tag("edit.png"), edit_plan_path(plan) %> | <%= link_to image_tag("delete.png"), plan, method: :delete, data: { confirm: 'Are you sure?' } %></span></div>
    <%= render :partial => "kpis/select", locals: {p_id: p_id} %>
  </li>
  <% end %>
   <% end %>
</ul>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Back', plans_path %>
</p>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @plan.goal %>
</p>

<p>
	<%= link_to 'Edit', edit_plan_path(@plan) %> |
	<%= link_to 'Back', plans_path %>
</p>

<p>
	<%= link_to 'Add new KPI', new_kpi_path(:plan_id=>@plan.id) %>
</p>

app/views/welcome/index.html.erb
<style type="text/css">
	html, body, ul, li { margin:0; padding:0; background-color:#151515;}
	ul, li { list-style-type:none; color:#b5e853; border:1px solid #3f3f3f; }
	ul.sTree, ul{ padding:0px; background-color:#151515; }
	ul.sTree2 li, ul#sortableListsBase li { padding-left:50px; margin:5px; border:1px solid #3f3f3f; background-color:#3f3f3f; }
	li div { padding:7px; background-color:#222; Nborder:1px solid #3f3f3f; }
	li, ul, div { border-radius: 3px; }
	.pT20 { padding-top:20px; }
	.pV10 { padding-top:10px; padding-bottom:10px; }
	.dN { display:none; }
	.dIB { display:inline-block; }
    .vAM { vertical-align: text-bottom; }
	.zI1000 { z-index:1000; }
	.small1 { font-size:0.8em; }
	.small2 { font-size:0.7em; }
	.small3 { font-size:0.6em; }
	.tAR { text-align:right; }
	.clear { clear:both; }
	img.descPicture { display:block; width:100%; margin:0 7px 30px 0; float:left; cursor:pointer; /*transition: all 0.5s ease;*/ }
	img.descPicture.descPictureClose { width:150px; }
	#sTree2 { margin:10px auto; }

</style>

<script src="http://code.jquery.com/jquery-git1.min.js"></script>
<script src="/assets/jquery-sortable-lists.js"></script>
<script type="text/javascript">
$(function()
{
	var options = {
		placeholderCss: {'background-color': '#ff8'},
		hintCss: {'background-color':'#bbf'},
        onChange: function( cEl )
        {
            console.log( 'onChange' );
        },
        complete: function( cEl )
        {
            console.log( 'complete' );
        },
		isAllowed: function( cEl, hint, target )
		{
			// Be carefull if you test some ul/ol elements here.
			// Sometimes ul/ols are dynamically generated and so they have not some attributes as natural ul/ols.
			// Be careful also if the hint is not visible. It has only display none so it is at the previouse place where it was before(excluding first moves before showing).
			if(hint.parents('li').first().data('module') === 'c' && cEl.data('module') !== 'c')
			{
				hint.css('background-color', '#ff9999');
				return false;
			}
			else
			{
				hint.css('background-color', '#99ff99');
				return true;
			}
		},
		opener: {
			 active: true,
			 close: '/assets/Remove2.png',
			 open: '/assets/Add2.png',
			 openerCss: {
				 'display': 'inline-block',
				 'width': '18px',
				 'height': '18px',
				 'float': 'left',
				 'margin-left': '-35px',
				 'margin-right': '5px',
				 'background-position': 'center center',
				 'background-repeat': 'no-repeat'
			 },
			 openerClass: ''
		},
		ignoreClass: 'clickable'
	};

	$('#sTree2, #sTree').sortableLists(options);

	$('#toArrBtn').on('click', function(){ console.log($('#sTree2').sortableListsToArray()); });
	$('#toHierBtn').on('click', function() { console.log($('#sTree2').sortableListsToHierarchy()); });
	$('#toStrBtn').on('click', function() { console.log($('#sTree2').sortableListsToString()); });
	$('.descPicture').on('click', function(e) { $(this).toggleClass('descPictureClose'); });

	$('.clickable').on('click', function(e)	{ alert('Click works fine! IgnoreClass stops onDragStart event.'); });

	/* Scrolling anchors */
	$('#toPictureAnch').on('click', function(e) { scrollToAnch('pictureAnch'); });
	$('#toBaseElementAnch').on('click', function(e) { scrollToAnch('baseElementAnch'); });
	$('#toBaseElementAnch2').on('click', function(e) { scrollToAnch('baseElementAnch'); });
	$('#toCssPatternAnch').on('click', function(e) { scrollToAnch('cssPatternAnch'); });

	function scrollToAnch(id)
	{
		$('html, body').animate({
			scrollTop: $("#" + id).offset().top
		}, 750);
		return false;
	}

});

</script>

<ul class="sTree2 listsClass" id="sTree2">
	<li>
		<div>Plan A Goal</div>
	</li>
	<li>
		<div>Plan B Goal</div>
		<ul>
			<li>
				<div>KPI Description</div>
				<div>KPI Responsibility</div>
				<div>KPI Milestone</div>
				<ul>
					<li>
						<div>Act Description</div>
						<div>Act Target</div>						
					</li>
				</ul>
			</li>
			<li>
				<div>Item b2</div>
			</li>
			<li>
				<div>Item b3</div>
			</li>
			<li>
				<div>Item b4</div>
			</li>
			<li>
				<div>Item b5</div>
			</li>
		</ul>
	</li>
	<li>
		<div>Item d</div>
		<ul>
			<li>
				<div>Item d1</div>
			</li>
			<li>
				<div>Item d2</div>
			</li>
			<li>
				<div>Item d3</div>
			</li>
			<li>
				<div>Item d4</div>
			</li>
			<li>
				<div>Item d5</div>
			</li>
		</ul>
	</li>
	<li>
		<div>Item e</div>
	</li>
</ul>